language: cpp
compiler:
  - gcc
  - clang
os: 
  - osx
osx_image: xcode11.4
addons:
  homebrew:
    packages:
      - cmake
      - gsl
      - boost
      - libomp
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
