language: cpp
compiler:
  - gcc
os: osx
osx_image: xcode9
dist: trusty
addons:
  homebrew:
    packages:
      - cmake
      - gsl
      - boost
script:
  - ls
  - mkdir build
  - cd build
  - cmake ..
  - make
